server:
  port: 8081

spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    schemas: orders

  jpa:
    properties:
      hibernate:
        default_schema: orders

order:
  url: ${ORDER_URL:http://order:8081}

product:
  url: ${PRODUCT_URL:http://product:8080}

exchange:
  url: ${EXCHANGE_URL:http://exchange:8080}
